### ISSUE TITLE
Incorrect logic

### ISSUE THREAD

**Issue by Zomis** [Azoraqua/Vanisher#1]
This will always return the same result:

`if(player.getGameMode() != GameMode.CREATIVE || player.getGameMode() != GameMode.SPECTATOR) {`

**Comment by Azoraqua** [comment]
That's not true. The body of that if statement only runs when the player is **not** in _Creative_ or _Spectator_ mode.

Which is exactly as it's stated.

**Comment by Zomis** [comment]
Okay, apparently you do not believe me so let's go through this:

Let's say that the game mode is something else, like `GameMode.SURVIVAL`:

    player.getGameMode() != GameMode.CREATIVE --> true
    player.getGameMode() != GameMode.SPECTATOR --> true
    true || true --> true

Now let's say that the game mode is `GameMode.CREATIVE`:

    player.getGameMode() != GameMode.CREATIVE --> false
    player.getGameMode() != GameMode.SPECTATOR --> true
    false || true --> true

Now let's say that the game mode is `GameMode.SPECTATOR`:

    player.getGameMode() != GameMode.CREATIVE --> true
    player.getGameMode() != GameMode.SPECTATOR --> false
    true || false --> true

See what happens? Your two conditions for the OR cannot both be false at the same time. One of them will always be true.

You say `The body of that if statement only runs when the player is not in Creative or Spectator mode.`
But what you are describing there is `if (!(player.getGameMode() == GameMode.CREATIVE || player.getGameMode() != GameMode.SPECTATOR))` which is **not the same thing**.

What the code **should** be is:

    if(player.getGameMode() != GameMode.CREATIVE && player.getGameMode() != GameMode.SPECTATOR) {

Note the use of `&&` instead of `||`

**Comment by Azoraqua** [comment]
What about if the player is in SURVIVAL mode for example?

**Comment by Zomis** [comment]
If the player is in SURVIVAL mode, then the body of the block will execute.

The problem is that given your current code the body **always** executes, even if the player is in CREATIVE or SPECTATOR.

**Comment by Azoraqua** [comment]
Thank you.
Sorry for my kinda stubbornness and unknownness. 

I've changed it to what you said.
